<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.tgcv</groupId>
    <artifactId>viatra-v002-observer-host</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>org.tgcv.viatra.v002.observer.runtime.test</artifactId>
  <packaging>eclipse-test-plugin</packaging>
  <dependencies>
    <dependency>
      <groupId>org.tgcv</groupId>
      <artifactId>org.tgcv.viatra.v002.observer</artifactId>
      <version>0.1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.tgcv</groupId>
      <artifactId>org.eclipse.viatra.examples.cps.xform.m2m.util</artifactId>
      <version>2.1.0-SNAPSHOT</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>target-platform-configuration</artifactId>
        <version>${tycho.version}</version>
        <configuration>
          <pomDependencies>consider</pomDependencies>
          <target>
            <artifact>
              <groupId>org.tgcv</groupId>
              <artifactId>tgcv-viatra-v002-target</artifactId>
              <version>${parent.version}</version>
            </artifact>
          </target>
          <dependency-resolution>
            <extraRequirements>
              <requirement>
                <type>eclipse-plugin</type>
                <id>org.eclipse.viatra.examples.cps.xform.m2m.util</id>
                <versionRange>0.0.0</versionRange>
              </requirement>
            </extraRequirements>
          </dependency-resolution>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.eclipse.tycho</groupId>
        <artifactId>tycho-surefire-plugin</artifactId>
        <version>${tycho.version}</version>
        <configuration>
          <dependencies>
            <dependency>
              <groupId>org.tgcv</groupId>
              <type>eclipse-plugin</type>
              <artifactId>org.eclipse.viatra.examples.cps.xform.m2m.util</artifactId>
              <version>[2.1.0,3.0.0)</version>
            </dependency>
          </dependencies>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>