<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.tgcv</groupId>
  <artifactId>viatra-v002-observer-host</artifactId>
  <version>0.1.0-SNAPSHOT</version>
  <properties>
    <maven.compiler.release>11</maven.compiler.release>
    <viatra.source.commit>ffa111dbb160c0bc55e89ea16430e97a38908662</viatra.source.commit>
    <viatra.query.runtime.version>1.2.0</viatra.query.runtime.version>
    <cps.model.version>1.2.0</cps.model.version>
    <cps.traceability.version>0.1.0</cps.traceability.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.eclipse.viatra.examples.cps</groupId>
      <artifactId>org.eclipse.viatra.examples.cps.model</artifactId>
      <version>1.2.0</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.viatra.examples.cps</groupId>
      <artifactId>org.eclipse.viatra.examples.cps.traceability</artifactId>
      <version>0.1.0</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.viatra</groupId>
      <artifactId>org.eclipse.viatra.query.runtime</artifactId>
      <version>1.2.0</version>
    </dependency>
  </dependencies>
</project>
