"""IT-G1 governed frozen case-evidence manifest generator.

Governance boundary:
- GitHub is the canonical source for this script and all canonical evidence.
- This script is executed locally only after synchronizing local main from origin/main.
- SHA-256 values are generated by code from the exact local working-tree bytes.
- The script never edits the canonical manifest or any evidence file.
- Its stdout is the generated manifest content; persistence of the resulting manifest
  revision must occur through the governed GitHub workflow, never by manual local edits.
- No AWS access or mutation is performed.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
EXEC_DIR = REPO_ROOT / "00_GOVERNANCE/INDUSTRIAL_TRACK/execution"

ROWS = [
    ("CASE-001", "unreachable_instance_id", ["IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_CASE_RESOURCE_FREEZE_001.md"]),
    ("CASE-002", "platform", ["IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_CASE_RESOURCE_FREEZE_001.md", "IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_SSM_MANAGED_NODE_OBSERVED_STATE_001.md"]),
    ("CASE-003", "instance_state", ["IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_CASE_RESOURCE_FREEZE_001.md"]),
    ("CASE-004", "root_volume_id", ["IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_ROOT_VOLUME_OBSERVED_STATE_001.md"]),
    ("CASE-005", "root_volume_encryption", ["IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_ROOT_VOLUME_ENCRYPTION_OBSERVED_STATE_001.md"]),
    ("CASE-006", "availability_zone", ["IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_CASE_RESOURCE_FREEZE_001.md"]),
    ("CASE-007", "subnet_id", ["IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_CASE_RESOURCE_FREEZE_001.md"]),
    ("CASE-008", "ssm_managed", ["IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_SSM_MANAGED_NODE_OBSERVED_STATE_001.md"]),
    ("CASE-009", "iam_prerequisites", ["IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_CALLER_IAM_SUPPORT_ACTION_AUTHORIZATION_SIMULATION_001.md", "IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_CALLER_EC2_MATERIAL_ACTION_AUTHORIZATION_SIMULATION_001.md", "IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_CALLER_SSM_EXECUTION_AUTHORIZATION_SIMULATION_001.md", "IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_INSTANCE_ROLE_SSM_POLICY_VERSION_002_OBSERVED_STATE_001.md", "IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_RUNBOOK_ASSUMEROLE_AND_NESTED_WORKFLOW_OBSERVED_STATE_001.md"]),
    ("CASE-010", "subnet_ssm_connectivity", ["IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_SSM_CONNECTIVITY_OBSERVED_STATE_001.md"]),
    ("CASE-011", "runbook_parameters", ["IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_RUNBOOK_PARAMETER_TUPLE_001.md"]),
    ("CASE-012", "rdp_context", ["IT-G1_AWSSUPPORT_EXECUTEEC2RESCUE_RDP_SYMPTOM_OBSERVED_STATE_001.md"]),
]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def main() -> int:
    hashes: dict[str, str] = {}
    for _, _, paths in ROWS:
        for path_text in paths:
            path = EXEC_DIR / path_text
            if not path.exists():
                raise SystemExit(f"EVIDENCE_MISSING={path_text}")
            hashes[path_text] = sha256(path)

    print("# IT-G1 — AWSSupport-ExecuteEC2Rescue")
    print("## Generated Case Evidence Manifest Revision")
    print()
    print("**Case:** `IT-G1-AWSSUPPORT-EXECUTEEC2RESCUE`")
    print("**Decision stage:** `PRE-DECISION`")
    print("**Manifest status:** `GENERATED — NOT YET FROZEN`")
    print("**Execution authorization:** `NONE`")
    print("**Local execution:** `NOT AUTHORIZED`")
    print()
    print("| Evidence ID | Decision field | Canonical evidence representation | SHA-256 |")
    print("|---|---|---|---|")
    for case_id, field, paths in ROWS:
        evidence = "; ".join(f"`{p}`" for p in paths)
        values = "; ".join(f"`{hashes[p]}`" for p in paths)
        print(f"| {case_id} | `{field}` | {evidence} | {values} |")

    print()
    print("Generation rule: SHA-256 values above were generated by this governed script from exact local working-tree bytes after synchronization with `origin/main`.")
    print("Persistence rule: this generated content is not canonical until committed through the governed GitHub workflow as a new manifest revision.")
    print("Execution boundary: `EXECUTION_AUTHORIZATION = NONE`; `AWSSUPPORT_EXECUTEEC2RESCUE_EXECUTED = FALSE`.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
